template: decaf-cli
answers:
  Description: Tasks is a task runner written in GO. Designed to be a simple task
    runner supporting both local development and ci/cd pipelines.
  Name: tasks
  Template: decaf-cli
  TemplateVersion: 0.0.1
  Timestamp: "2019-11-11T21:00:08Z"
