# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# This file is a template, and might need editing before it works on your project.
# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: golang:1.11-alpine
# image: node:8.11-alpine

variables:
  PROJECT_PATH: "/go/src/github.com/techdecaf/cgen"

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - $CI_PROJECT_DIR/dist

stages:
  - test
  - deploy

test:
  image: golang:1.13-alpine
  stage: test
  script:
    - apk add git
    - go run . list
    - go run . run build

deploy:
  image: techdecaf/ci:1.2.0
  stage: deploy
  script:
    - ./dist/linux/tasks run install
    - eval $(tasks run login --log false)
    - echo $AWS_ROLE_NAME
  only:
    # - master
