# FULL DOCUMENTATION CAN BE FOUND HERE: #https://docs.gitlab.com/ce/ci/yaml/

# image: golang:1.13-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache

cache:
  paths:
    - $CI_PROJECT_DIR/dist

stages: [test, deploy]

test:
  image: golang:1.13-alpine
  stage: test
  script:
    - apk add git
    - go run . list
    - go run . run build

deploy:
  image: techdecaf/ci:v1.3.0
  stage: deploy
  script:
    - ./dist/linux/tasks run install
    - eval $(tasks run login --log false)
    - tasks run publish
  only: [master]
  except: { changes: ["*.md"] }
