options:
  log: true # debug, info, error, silent


# all task variables are environmental variables, if they do not already exist in the current
# environment, then you can set them here using the golang template syntax
variables:
  # Get the current working directory and extract the base path
  CI_PROJECT_NAME: "{{ReadFile `.cgen.yaml` | YQ `answers.Name`}}" # === tasks
  # TRY to execute git describe --tags, defaults to an empty string
  CI_COMMIT_TAG: "{{TRY `git describe --tags --always --dirty --abbrev=0`}}"
  # TRY to get the current branch name using git rev-parse
  CI_COMMIT_REF_NAME: "{{TRY `git rev-parse --abbrev-ref HEAD`}}"
  # TRY to get the current commit sha
  CI_COMMIT_SHA: "{{TRY `git rev-parse HEAD`}}"
  # Sets a static value
  S3_BUCKET: github.techdecaf.io
  # use the dot variable syntax to template the following url from variables
  DOWNLOAD_URI: http://{{.S3_BUCKET}}/{{.CI_PROJECT_NAME}}

tasks:
  default:
    description: is the task that runs when no tasks have been specified. `tasks run` == `tasks run default`
    commands: [tasks list]

  dependencies:
    description: install all required dependencies
    commands: [go get, go install]

  build:
    description: compile window, linux, osx x64
    pre: [clean, dependencies]
    variables:
      flags: build -ldflags "-X main.VERSION={{.CI_COMMIT_TAG}}"
    commands:
      - GOOS=darwin go {{.flags}} -o build/darwin/{{.CI_PROJECT_NAME}} -v
      - GOOS=linux go {{.flags}} -o build/linux/{{.CI_PROJECT_NAME}} -v
      - GOOS=windows go {{.flags}} -o build/windows/{{.CI_PROJECT_NAME}}.exe -v

  clean:
    description: removes all files listed in .gitignore
    commands: ["rm -rf build temp"]

  install:
    description: installs locally to /usr/local/bin
    commands:
      - "chmod +x build/{{OS}}/{{.CI_PROJECT_NAME}}"
      - "cp build/{{OS}}/{{.CI_PROJECT_NAME}} /usr/local/bin"

  upload:
    description: moves compiled files to /usr/local/bin/
    commands: ["aws s3 sync build s3://{{.S3_BUCKET}}/{{.CI_PROJECT_NAME}}/{{.CI_COMMIT_TAG}}"]

  publish:
    description: publish new stable version under the `latest` tag
    commands: ["aws s3 sync build s3://{{.S3_BUCKET}}/{{.CI_PROJECT_NAME}}/latest"]

  login:
    description: checkout temporary aws access keys
    commands:
      - curl -s "$DECAF_URL/keys/aws/set/env/linux/website-update?jwt=$DECAF_TOKEN"

  docs:
    description: auto generate documentation
    commands:
      # expand the file, and pipe to write, if no errors default to the string "success"
      - "echo {{ExpandFile `docs/README.md` | WriteFile `README.md` | default `docs updated`}}"

  test:
    description: run tests
    pre: [clean]
    commands:
      - go run . help
      - go run . list

  upgrade:
    description: upgrade project from cgen template
    commands: ["cgen upgrade"]

  # coverage:
  #   description: run test coverage
  #   commands:
  #     - "go test ./app -coverprofile coverage.out && go tool cover -func=coverage.out"

  pre-release:
    description: bump patch version and release for deployment
    commands:
      - cgen bump --level pre-release
      - git push --follow-tags --no-verify

  release-patch:
    description: bump patch version and release for deployment
    commands:
      - cgen bump --level patch
      - git push --follow-tags --no-verify

  release-minor:
    description: bump minor version and release for deployment
    commands:
      - cgen bump --level minor
      - git push --follow-tags --no-verify

  upgrade:
    description: upgrade the current project
    commands: [cgen upgrade, yarn upgrade --latest]

  oops:
    description: undo last commit
    commands: [git reset HEAD~1]
